
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
spec:
  rules:
    - host: {{ .Values.ingress.hosts.mlflow }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow-svc
                port:
                  number: 5000
